### ISSUE TITLE
A question about the experiment results in your paper

### ISSUE THREAD

**Issue by cloudcjf** [lilin-hitcrt/SSC#1]
Hi, thanks for your work and code. I notice that the F1 max score of SG_PR is quite different, actually much lower, in your paper. I'm quite interested in a place recognition task, so I'd like to go deep into details. Did I miss any key points? Could you please explain the result? Thanks and best wishes.

**Comment by lilin-hitcrt** [comment]
> Hi, thanks for your work and code. I notice that the F1 max score of SG_PR is quite different, actually much lower, in your paper. I'm quite interested in a place recognition task, so I'd like to go deep into details. Did I miss any key points? Could you please explain the result? Thanks and best wishes.

Hello! Thanks for your question. 
Our test data selection strategy is slightly different from SG_PR. In SG_PR's paper, negative samples are randomly selected according to a certain probability. In our experiments, we found that the proportion of negative samples selected according to the above method is too small, so the results of most methods are relatively high. To highlight the gap between different methods, we set more stringent test conditions; more negative samples are selected. The selection strategy is specifically described in our paper; that is, negative samples are selected according to a fixed ratio (1,10,20,50,100). The number of negative samples in Table 1 is 100 times that of positive samples, which is much higher than the ratio used in the SG_PR paper. You can download the list of test samples through this [link](https://drive.google.com/file/d/1Y540LJFZHiaAooUX2KtxNIQhw-kzy7gQ/view?usp=sharing).

**Comment by cloudcjf** [comment]
Thanks! That seems to be a valid explanation. Also, your consideration has broadened my mind. Thanks again for your great work.
