### ISSUE TITLE
Question about integration SSC to Lidar Odometry package

### ISSUE THREAD

**Issue by giangdao1402** [lilin-hitcrt/SSC#11]
@lilin-hitcrt 
Thanks for your great work!

I have a question about integrating to Lidar Odometry package such as [FAST_LIO](https://github.com/hku-mars/FAST_LIO)
I know there is already have Scan Context (Kim) integrate into FAST_LIO to perform loop closure
Is it possible to get semantic data when run FAST_LIO and using SSC to perform loop closure as well ?

I would appreciate it if you could give me an engineering tip. 😄

Thanks,

**Comment by lilin-hitcrt** [comment]
Thanks for the issue. It seems similar to #6 and #8. Please check those for solutions. Let us know if you need further assistance.

**Comment by giangdao1402** [comment]
Thanks for the issue that you refer to, so that in theory i can run Inference of RangeNet++ and finally i can have SSC based LIO that can perform loop closure ?
