### ISSUE TITLE
Confusion about parameters 

### ISSUE THREAD

**Issue by giangdao1402** [lilin-hitcrt/SSC#12]
@lilin-hitcrt 
Thanks for your great work!

I have a question about those parameters in your code: bool rotate, bool occlusion, bool remap, float random_angle, float max_angle, float cs, float ss

I would appreciate it if you could give me a explanation

Thanks,

**Comment by lilin-hitcrt** [comment]
**remap:** Used for converting labels from KITTI-360 format to KITTI format. If using the KITTI-360 dataset, set it to True.

Other parameters are used for robustness testing.
**bool rotate (Default: False):** If True. Perform random rotation. Test the algorithm's robustness to viewpoint change (rotation).
**bool occlusion (Default: False):** If True. Perform random occlusion. Test the algorithm's robustness to (random) occlusion.
**random_angle and max_angle**: If random occlusion is performed, remove the point cloud between random_angle and max_angle (Yaw direction).
**float ss, float cs:** Sine and cosine values of the (random) rotation angle.
