### ISSUE TITLE
What is your evaluation setting on EP score?

### ISSUE THREAD

**Issue by cloudcjf** [lilin-hitcrt/SSC#3]
Hi, thanks for your open-source code which includes the results of those compared methods. However, I haven't found any part of the code to calculate the EP score. Would you please illustrate more details on this topic? Is the evaluation pair lists still be neg_100 as you mentioned in #1 for the F1 max score? How will you then define PR0 and RP100 since the pair list is not constructed by order?

**Comment by lilin-hitcrt** [comment]
> Hi, thanks for your open-source code which includes the results of those compared methods. However, I haven't found any part of the code to calculate the EP score. Would you please illustrate more details on this topic? Is the evaluation pair lists still be neg_100 as you mentioned in #1 for the F1 max score? How will you then define PR0 and RP100 since the pair list is not constructed by order?

1. Yes, the evaluation pair lists still be neg_100. 
2. We use [sklearn](https://github.com/scikit-learn/scikit-learn) to get the PR curve (see [this file](https://github.com/lilin-hitcrt/SSC/blob/main/script/pr_curve.py)). Then PR0 and RP100 can be easily found from the curve.
