### ISSUE TITLE
A question on evaluation time

### ISSUE THREAD

**Issue by cloudcjf** [lilin-hitcrt/SSC#4]
Hi, thanks again for your code and evaluation results. I'm reproducing the results of your method and the program is quite slow when I run ./eval_seq in the bin folder. As a result, it would take a long time to test even one sequence. So I tend to try the eval_pair. Again, it takes 10109ms to do "ssc.getScore" function. In your paper, however, the average time of making descriptors is approx 2.563 ms. Have I missed any details?  My platform info: Intel(R) Core(TM) i7-9800X CPU @ 3.80GHz.

**Comment by cloudcjf** [comment]
I've just restarted my Desktop and the time cost is still the same as before. It will take almost 20 days if I'd like to generate the pairs'  similar scores of sequence 07, which is the smallest sequence, following the neg_100 strategy, let alone the other sequences. Please help~~~THX in advance!

**Comment by lilin-hitcrt** [comment]
> Hi, thanks again for your code and evaluation results. I'm reproducing the results of your method and the program is quite slow when I run ./eval_seq in the bin folder. As a result, it would take a long time to test even one sequence. So I tend to try the eval_pair. Again, it takes 10109ms to do "ssc.getScore" function. In your paper, however, the average time of making descriptors is approx 2.563 ms. Have I missed any details? My platform info: Intel(R) Core(TM) i7-9800X CPU @ 3.80GHz.

Hello, can you provide the time consuming of each part of the program?  (data loading, projection, icp, computing descriptor, and matching)
