### ISSUE TITLE
A question about the contribution of semantic data

### ISSUE THREAD

**Issue by MohammedCHGHAF** [lilin-hitcrt/SSC#5]
Hi, thank you very much for your great work and for the code. 

I have read your paper and I appreciated the level of information that you provided. However I still have a question about the encoding function that you have used for your descriptor when you didn't use semantic data (while calculating the contribution of individual components).

Can you please share the block representation used and the similarity score used in this case ? 

Thank you very much !
Best regards

**Comment by lilin-hitcrt** [comment]
> Hi, thank you very much for your great work and for the code.
> 
> I have read your paper and I appreciated the level of information that you provided. However I still have a question about the encoding function that you have used for your descriptor when you didn't use semantic data (while calculating the contribution of individual components).
> 
> Can you please share the block representation used and the similarity score used in this case ?
> 
> Thank you very much ! Best regards

Hi, you can refer to the ‘makeScancontext’ and ‘distanceBtnScanContext’ functions in the original Scan Context ([paper](https://ieeexplore.ieee.org/document/8593953), [code](https://github.com/irapkaist/scancontext/blob/master/cpp/module/Scancontext/Scancontext.cpp)).

**Comment by MohammedCHGHAF** [comment]
Thanks for the suggestion ! 
& thanks again for your great work !

**Comment by PigletPh** [comment]
@MohammedCHGHAF hi，I have a question to ask you.How to get semantic data,like 000720.label and 001500.label?
