### ISSUE TITLE
The problem of porting SSC to loam

### ISSUE THREAD

**Issue by PigletPh** [lilin-hitcrt/SSC#6]
@lilin-hitcrt Hello, I have read your article, thank you very much for your excellent work. I am now trying to port SSC to the LOAM algorithm. I have any questions. 
   I would like to ask: I have a 16-line lidar. If I want to run the SSC-based LOAM algorithm in real time, where does the semantic label come from, and what other issues do I need to pay attention to?
 Looking forward to your reply！

**Comment by lilin-hitcrt** [comment]
I'm sorry for the late reply. In our experiment, we adopt [RangeNet++](https://github.com/PRBonn/lidar-bonnetal) to obtain semantic information. They also provided [code](https://github.com/PRBonn/rangenet_lib) to accelerate inference using TensorRT.  Maybe you can try to retrain their network on your own dataset. You can also try some of the latest semantic segmentation algorithms, such as [Cylinder3D](https://github.com/xinge008/Cylinder3D).

**Comment by lilin-hitcrt** [comment]
Since there is no further update about this issue, I will close it. If you have any questions, please feel free to reopen it.
