### ISSUE TITLE
A question about the results based on the provided evaluation sample

### ISSUE THREAD

**Issue by ShutongJIN** [lilin-hitcrt/SSC#7]
Thank you so much for your code and detailed explanation, it's of great help to me.
And I have a few questions about the data used for ploting p-r curves. As you said, the first column of each data file is the similarity score, and the second column is the ground truth. I wonder whether all the similarity scores are obtained through the similarity scoring mentioned in the paper. Because there are numbers bigger than 1 in some of the files, for example, results/kitti/neg_100/SC/00.txt.
Another question is that about the evaluation samples. I noticed that only pairs are provided, but how to measure the effectiveness of the topk candidates? As usually 25 candidates are generated for each query frame, but it seems to me that only one candidate is evaluated.
Thanks a lot and I really appreciate it if you can reply to me at your earliest convenience:)

**Comment by lilin-hitcrt** [comment]
> Thank you so much for your code and detailed explanation, it's of great help to me. And I have a few questions about the data used for ploting p-r curves. As you said, the first column of each data file is the similarity score, and the second column is the ground truth. I wonder whether all the similarity scores are obtained through the similarity scoring mentioned in the paper. Because there are numbers bigger than 1 in some of the files, for example, results/kitti/neg_100/SC/00.txt. Another question is that about the evaluation samples. I noticed that only pairs are provided, but how to measure the effectiveness of the topk candidates? As usually 25 candidates are generated for each query frame, but it seems to me that only one candidate is evaluated. Thanks a lot and I really appreciate it if you can reply to me at your earliest convenience:)

1. Some methods such as SC use the distance between descriptors to measure the similarity between point clouds; the closer the distance, the greater the similarity. To draw the PR curve correctly, we use the inverse of the distance as the similarity.
2. In our experiments, we randomly select positive and negative samples for experiments. If you want to  measure the effectiveness of the top-k candidates, please refer to [this file](https://github.com/lilin-hitcrt/SSC/blob/main/eval_top1.cpp). You can access our experimental results via this [link](https://github.com/lilin-hitcrt/SSC/tree/main/script) ([00.txt](https://github.com/lilin-hitcrt/SSC/blob/main/script/00.txt), [02.txt](https://github.com/lilin-hitcrt/SSC/blob/main/script/02.txt), [05.txt](https://github.com/lilin-hitcrt/SSC/blob/main/script/05.txt), [06.txt](https://github.com/lilin-hitcrt/SSC/blob/main/script/06.txt), [07.txt](https://github.com/lilin-hitcrt/SSC/blob/main/script/05.txt), [08.txt](https://github.com/lilin-hitcrt/SSC/blob/main/script/05.txt)). The first column in each file represents the target, and the remaining columns represent top-k candidates. We also provide the [code](https://github.com/lilin-hitcrt/SSC/blob/main/script/recall.py) to draw the curve.

**Comment by ShutongJIN** [comment]
Thank you so much! I shall close the issue now.
