### ISSUE TITLE
How to get the label for kitti dataset?

### ISSUE THREAD

**Issue by PigletPh** [lilin-hitcrt/SSC#8]
@lilin-hitcrt Hi,I want to know how to get the label of the pointcloud,such as KITTI/odometry/dataset/sequences/08/labels/.Is there any link can I download?Thanks for your answer!

**Comment by lilin-hitcrt** [comment]
> @lilin-hitcrt Hi,I want to know how to get the label of the pointcloud,such as KITTI/odometry/dataset/sequences/08/labels/.Is there any link can I download?Thanks for your answer!

Hello! You can download the ground-truth labels from [semantic kitti](http://www.semantic-kitti.org/assets/data_odometry_labels.zip). Also, you can use some excellent semantic segmentation algorithms, such as [RangeNet++](https://github.com/PRBonn/rangenet_lib), and [Cylinder3D](https://github.com/xinge008/Cylinder3D), to generate labels.

**Comment by PigletPh** [comment]
@lilin-hitcrt Thanks,I will have a try.Another problem is that can you provide the source code for other Classic LCD Algorithms such as sc,overlapnet  on kitti ,not the results(.txt),thanks!

**Comment by lilin-hitcrt** [comment]
> @lilin-hitcrt Thanks,I will have a try.Another problem is that can you provide the source code for other Classic LCD Algorithms such as sc,overlapnet on kitti ,not the results(.txt),thanks!

Sorry for not replying in time as I was preparing for ICRA2023 some time ago. The source codes of all the methods compared in the paper can be obtained from the github.
