### ISSUE TITLE
Protocol to determine gt loop closure in evaluation

### ISSUE THREAD

**Issue by lewisjiang** [lilin-hitcrt/SSC#9]
Dear authors,

Recently I've been reading the code of SSC and RINet. I find that during evaluation, one needs pairing files with paths like `/pairs_kitti/neg_100/00.txt'`. However, I don't see any scripts directly generating these pairing files ended with `.txt`. So I'm wondering if they are generated with some other scripts from the `.npz` file produced by `gen_pairs.py`? And does that mean you avoid to evaluate (or define PN for) any pairs of poses with their distances between 3m and 20m?

Thanks a lot and hope to get your reply!

**Comment by lilin-hitcrt** [comment]
> Dear authors,
> 
> Recently I've been reading the code of SSC and RINet. I find that during evaluation, one needs pairing files with paths like `/pairs_kitti/neg_100/00.txt'`. However, I don't see any scripts directly generating these pairing files ended with `.txt`. So I'm wondering if they are generated with some other scripts from the `.npz` file produced by `gen_pairs.py`? And does that mean you avoid to evaluate (or define PN for) any pairs of poses with their distances between 3m and 20m?
> 
> Thanks a lot and hope to get your reply!

Hello,
Thank you for following our work. In order to facilitate the c++ code to read the data, we convert the 'npz' file into a 'txt' file. You can get the 'txt' file by following steps: 
1.  Randomly sample some negative samples: np.random.shuffle(id_neg) -> id_neg = id_neg[ : 100 * len(id_pos)]
2.  Concatenate positive samples with negative samples: data = np.concatenate([id_pos, id_neg], axis = 0 )
3. save as txt file：replace np.savez() as np.savetxt(data ,  'test.txt').

**Comment by lewisjiang** [comment]
@lilin-hitcrt Thank you for the sample code. 

So if I understand correctly, neither the training nor testing uses pose pairs with distances between 3m and 20m, right? 

And in the paper, this protocol is said to be inherited from SG_PR. I notice there are many other gt protocols around (e.g. true positive if the distance between the candidates is less than t meters), and instead of giving a PN prediction for every pair, some choose the most similar visited pose for loop PN prediction (e.g. LCDNet) which better simulates the real-world application. So I'm wondering are there any specific reasons for choosing the protocol that predicts pairwisely and skips intermediate distances?

Thanks again and hope to hear your comments!

**Comment by lilin-hitcrt** [comment]
> @lilin-hitcrt Thank you for the sample code.
> 
> So if I understand correctly, neither the training nor testing uses pose pairs with distances between 3m and 20m, right?
> 
> And in the paper, this protocol is said to be inherited from SG_PR. I notice there are many other gt protocols around (e.g. true positive if the distance between the candidates is less than t meters), and instead of giving a PN prediction for every pair, some choose the most similar visited pose for loop PN prediction (e.g. LCDNet) which better simulates the real-world application. So I'm wondering are there any specific reasons for choosing the protocol that predicts pairwisely and skips intermediate distances?
> 
> Thanks again and hope to hear your comments!

Sorry for not replying in time as I was preparing for ICRA2023 some time ago. Maybe you can try Recall@k. This indicator does not have the above problems. We have provided the relevant code for calculating Recall@k.

**Comment by lewisjiang** [comment]
Thank you for your advice and I've read about different GT protocols and their pros and cons in the past months.
